### ISSUE TITLE
Correctly quote all possible booleans.

### ISSUE THREAD

**Issue by hrach** [chyh1990/yaml-rust#53]
Currently, the library incorrectly doesn't add quotes to strings, which will be interpreted as booleans:
https://github.com/chyh1990/yaml-rust/blob/bbe06964006ef8c12cd1f08b00bd6a95a0e752d1/src/emitter.rs#L270-L271

Specs describes many other possiblities:
http://yaml.org/type/bool.html

Personally, I encounter this bug with string `TRUE` in https://github.com/InQuicker/ktmpl/ which produced such value without qutes and kubernetes doesn't accept that value.

**Comment by dtolnay** [comment]
Thanks for catching this. We would love a PR to fix this!

**Comment by hoodie** [comment]
careful here! these bools are path of the yaml **1.1** specification, this parser is supposed to be a **1.2** compatible parser - things like `yes == true` have been removed in **1.2**

**Comment by Byron-TW** [comment]
It would be great if these (previously) valid boolean values ("YES", for example) are always quoted anyway to assure the other side will always decode it as a string. `kubectl` for example validates the parsed yaml and aborts if booleans are encountered instead of strings.

Leaving them quoted is harmless for version 1.2, and means version 1.1 validations aren't broken unnecessarily.

**Comment by hoodie** [comment]
@hrach sorry I misread your issue there
does this perhaps do the trick? (#72)

**Comment by Byron-TW** [comment]
@hoodie For me that would do it perfectly! Once that issue lands, my problem would be solved. For now we solved it by actually changing the consumer code, which luckily was in our reach.

**Comment by hrach** [comment]
Yes, that seems to be the correct fix. Sorry for writing so unclear issue :-)
